### ISSUE TITLE
Unknown De/Serialization Error

### ISSUE THREAD

**Issue by EqLogic** [EqLogic/Ulmeta-Chat#7]
Type: System.Runtime.Serialization.SerializationException
System.Runtime.Serialization.SerializationException: Binary stream '0' does not
contain a valid BinaryHeader. Possible causes are invalid stream or object versi
on change between serialization and deserialization.
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(He
aderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAp
pDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize
(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCr
ossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize
(Stream serializationStream)
   at InterData.Packet..ctor(Byte[] packet_bytes) in c:\Users\Admin\Documents\Ul
meta-Chat\InterData\Packet.cs:line 70
   at ServerConsole.ServerConsole.ReadData(Object socket) in c:\Users\Admin\Docu
ments\Ulmeta-Chat\ServerConsole\ServerConsole.cs:line 124

**Comment by EqLogic** [comment]
[1/9/2015 11:04:42 PM] System.NullReferenceException: Object reference not set to an instance of an object.
   at ClientInterface.NetworkModule.get_IP() in c:\Users\Admin\Documents\Ulmeta-Chat\ClientInterface\NetworkModule.cs:line 40
   at ClientInterface.NetworkModule.ReadData() in c:\Users\Admin\Documents\Ulmeta-Chat\ClientInterface\NetworkModule.cs:line 127

**Comment by EqLogic** [comment]
Unseen since 1/9/15

**Comment by EqLogic** [comment]
Unseen Since 1/9/15 - closing issue; was probably handled with implementation of exception handling for serialization of packets.
