### ISSUE TITLE
Disconnection of one client can cause all clients to disconnect.

### ISSUE THREAD

**Issue by EqLogic** [EqLogic/Ulmeta-Chat#8]
[1/11/2015 12:38:57 AM] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/
[1/11/2015 12:38:57 AM] System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/
[1/11/2015 12:39:00 AM] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/
[1/11/2015 12:39:00 AM] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/
[1/11/2015 12:39:00 AM] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/
[1/11/2015 12:39:00 AM] System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.Socket.Receive(Byte[] buffer)
   at ServerConsole.ServerConsole.ReadData(Object socket)
/!/

**Comment by EqLogic** [comment]
Failure does not occur immediately, rather after the first message sent by a 'disconnected' client.

Define Port With Which To Bind: 2502
Server Initialized On [10.0.0.6] @ 12:49:19 AM
Client Attached: <Enroq> [0e69db94-d096-4c3b-8740-3260b2e1704e]
Client Attached: <Enroq2> [1f193f5e-916b-4413-9a14-6b793dda6d98]
[24.127.38.163:51778] Disconnected..
[24.127.38.163:51783] Disconnected..
(12:50:46 AM) [Enroq <0e69db94>]: Test.

**Comment by EqLogic** [comment]
https://github.com/EqLogic/Ulmeta-Chat/commit/5355fc0675d9cb8494441f46d7840caa8e784015
